name    'puppetlabs-awsdemo_profiles'
version '0.1.0'
source 'https://github.com/puppetlabs/puppetlabs-awsdemo_profiles'
author 'Gary Larizza / Puppet Labs'
license 'Apache2'
summary 'Puppet module to manage "profiles" and higher-level abstractions'
description 'Manages configurations through the use of utility modules'
project_page 'https://github.com/puppetlabs/puppetlabs-awsdemo_profiles'

## Add dependencies, if any:
dependency 'hunner/wordpress', '>= 0.4.0'
dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'puppetlabs/mysql', '>= 2.0.0'
dependency 'thias/vsftpd', '>= 0.1.0'
dependency 'puppetlabs/firewall', '>= 0.4.0'
dependency 'puppetlabs/java', '>= 1.0.0'
dependency 'rtyler/jenkins', '>= 0.2.4'
